### ISSUE TITLE
iat (Issued At) claim is not valid - Google Provider/Login

### ISSUE THREAD

**Issue by LeahCram** [ADmad/cakephp-social-auth#82] opened 2020-09-03 18:27 UTC
I used this plugin on my app. Facebook Login is working. But when I tried the Google Login/Provider. I got this error.

![image](https://user-images.githubusercontent.com/11911663/92153013-33178900-ee56-11ea-971d-13d4e3fd5e14.png)

**Comment by ADmad** [comment] 2020-09-03 19:14
Duplicate of https://github.com/SocialConnect/auth/issues/118

**Closed by ADmad** 2020-09-03 19:14 UTC
