### ISSUE TITLE
Expression SocialProfiles.identifier is missing operator (IS, IS NOT) with null value.

### ISSUE THREAD

**Issue by L4suicide** [ADmad/cakephp-social-auth#99] opened 2021-05-11 22:34 UTC
I've been using this plugin for a while (thank you very much!) on 3.x and have recently been working on upgrading my site to 4.x

Post upgrade I am getting an error during the callback

> Expression SocialProfiles.identifier is missing operator (IS, IS NOT) with null value.

I've tracked down that this line is providing null values (yet in 3x the same users can log in ok)

SocialAuthMiddleware Line 317:
`$identity = $provider->getIdentity($accessToken);`

I've gone through the docs, re-created the users, and I can't work out why it's not returning the identity.

This is my Application.php config
```

->add(new \ADmad\SocialAuth\Middleware\SocialAuthMiddleware([
                // Request method type use to initiate authentication.
                'requestMethod' => 'POST',
                // Login page URL. In case of auth failure user is redirected to login
                // page with "error" query string var.
                'loginUrl' => '/users/login',
                // URL to redirect to after authentication (string or array).
                'loginRedirect' => '/',
                // Boolean indicating whether user identity should be returned as entity.
                'userEntity' => false,
                // User model.
                'userModel' => 'Users',
                // Social profile model.
                'socialProfileModel' => 'ADmad/SocialAuth.SocialProfiles',
                // Finder type.
                'finder' => 'all',
                // Fields.
                'fields' => [
                    'password' => 'password',
                ],
                // Session key to which to write identity record to.
                'sessionKey' => 'Auth',
                // The method in user model which should be called in case of new user.
                // It should return a User entity.
                'getUserCallback' => 'getUser',
                // SocialConnect Auth service's providers config. https://github.com/SocialConnect/auth/blob/master/README.md
                'serviceConfig' => [
                    'provider' => [
                        'discord' => [                        
                            'applicationId' => '12345',
                            'applicationSecret' => 'xxx-xxx',
                            'scope' => [
                                'identify',
                                'email'
                            ]
                        ],
                    ],
                ],

```
Is this a bug? Or am I missing something obvious?

**Comment by ADmad** [comment] 2021-05-12 03:44
I don't see how return value of `$provider->getIdentity($accessToken)` could be null. `getIdentity()` method of provider classes of always return an object. It's more like that `$identity->id` uses on line 331 is null.

The discord provider doesn't specify any mapping for the `id` field of the identity entity https://github.com/SocialConnect/auth/blob/2f8fbe302a99bf97d19a1fec54c4db56127f52a2/src/OAuth2/Provider/Discord.php#L75 so perhaps that might be the issue.

**Comment by L4suicide** [comment] 2021-05-12 07:30
> I don't see how return value of `$provider->getIdentity($accessToken)` could be null. `getIdentity()` method of provider classes of SocialConnect/Auth always return an object. It's more like that `$identity->id` used on line 331 is null.
> 
> The discord provider doesn't specify any mapping for the `id` field of the identity entity, https://github.com/SocialConnect/auth/blob/2f8fbe302a99bf97d19a1fec54c4db56127f52a2/src/OAuth2/Provider/Discord.php#L75 so perhaps that might be the issue.
> 
> So you should debug the `$response` object there and check.

Sorry yes the entire object is full of null values.

> 
> ^ SocialConnect\Common\Entity\User {#149 ▼
>   +id: null
>   +firstname: null
>   +lastname: null
>   +email: null
>   +emailVerified: true
>   #birthday: null
>   +username: null
>   #sex: null
>   +fullname: null
>   +pictureURL: null
> }

$response in the Discord provider:

```
^ array:10 [▼
  "id" => "121389831938"
  "username" => "MyUsername!"
  "avatar" => "fafasfas"
  "discriminator" => "1267"
  "public_flags" => 0
  "flags" => 0
  "locale" => "en-US"
  "mfa_enabled" => true
  "email" => "secret@removed.com"
  "verified" => true
]
```
Appears the ArrayHydrator()->hydrate is not working as expected from socialconnect (auth@ 3.2.2, jwx @ 1.2.0)

Is there a specific version of socialconnect/auth I can test with that you used originally?

**Comment by ADmad** [comment] 2021-05-12 07:46
The issue is related specifically to the Discord provider, which I have never used before.

To fix the issue you can submit a patch to socialconnect/auth updating the field mapping array for the `ArrayHydrator`, so that `id` and other fields of the identity are properly set.

**Comment by ADmad** [comment] 2021-05-12 16:23
Closing as a PR has been opened for SocialConnect/auth to update the field mapping.

**Closed by ADmad** 2021-05-12 16:23 UTC
